apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
