#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODAxZWI0ZDQ4MDgzZWIxODVkYzZlYzk0MzBjOWZjMDk1YjUyMTNmOTJhMzRmYjFjZGRjODlhYWMwOTUwMDZkNmQ5OGQwZDEzNjEzMjk3YWQ1MTljNTBjZDQyZjJkY2Y4NjA2NWNlMmRhYzQ3OTY5YzI3NmZkZjliZTEzNTI2MzQ=
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
